SecureApiGateway/secure-api-gateway-releases

Makefile
Update makefile for publish_helm to echo a general error message if uploading to repository fails
We need this as without if a package already exists the pipeline will fail, instead of trying to upload the other packages where there may be changes to upload
=> 935: Workflow changes based on feedback from release 1.0.0

kustomize/overlay/7.2.0/defaults/kustomization.yaml, secure-api-gateway-helpers/Chart.yaml, secure-api-gateway/Chart.yaml, third-party/Chart.yaml
Specify what versions of the child items will be used for version 1.0.1 of the secure-api-gateway helm umbrella charts.
Secure API Gateway: 1.0.0 > 1.0.1
IG: 1.0.0 > 1.0.1
remote-consent-service: 1.0.0 > 1.0.1
test-facility-bank: 1.0.0 > 1.0.1
remote-consent-service-user-interface: 1.0.1 > 1.0.2
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/969
Releases
- https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/383 
- https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/173
- https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs/pull/128
- https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs/pull/129
- https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-ui/pull/96
- …
=> 969: Increment versions to be deployed for 1.0.1 Helm Package release

kustomize/overlay/7.2.0/defaults/deployment.yaml, kustomize/overlay/7.2.0/defaults/kustomization.yaml, secure-api-gateway/Chart.yaml
- Updated deployment so that IG has 3 replicas 
- Changed kustomization.yaml so that version 1.0.2 is used for IG
- Updated child values in umbrella chart to pick up new changes
Deployment: https://github.com/SecureApiGateway/SecureApiGateway/issues/995
=> 995: sapig release 1.0.2

kustomize/overlay/7.2.0/defaults/ingress.yaml
Change `http2-max-header-size` to `large-client-header-buffers` & remove obsolete `http2-max-field-size`
This will tie in with the update from nginx 4.2.0 -> 4.8.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/918
=> 918: Update annotations for nginx

postman/v2.0/postman_scripts/client_jws_helpers.js
This will allow us to maintain and add different methods as needed and maintain the pre-request script in one place.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1171
=> 1171: Add function to set client_credential request headers

postman/v2.0/postman_scripts/client_jws_helpers.js
The consent type last created is stored in an environment variable. This allows multiple consentIds to be stored at any time for later use and also allows one consent request to handle the many consent types which dramatically reduces the duplication of requests and code across the postman collection
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1171
=> 1171: Add script to obtain consent Id

postman/v2.0/postman_scripts/client_jws_helpers.js
Different SAPI-G deployments need to support different acr values being requested in /authorize calls.
Adding new environment variable AUTHORIZE_REQUEST_ACR to control the acr value, defaulting this to `urn:openbanking:psd2:ca` for backwards compatibility.
Plain Fapi Postman environment will be configured to use `urn:mace:incommon:iap:silver`
https://github.com/SecureApiGateway/SecureApiGateway/issues/1298
=> 1298: Support making acr value requested in /authorize calls configurable

ob/secure-api-gateway-ob/Chart.yaml
Bump OB Chart version to 2.4.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1313
=> 1313: Update Repos for having Core and OB SAPIG

.github/workflows/release.yaml
Temp fix to get build working, remove steps to call to parent workflows and create tag and release manually
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1433
=> 1433: Update Release workflows for Secure Api Gateway Release & Helpers

ob/kustomize/overlay/7.3.0/defaults/kustomization.yaml
Correct URL for OB Kustomise to get config from core
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
=> 1404: Create and Release SAPIG Core and OB

postman/v2.0/postman_scripts/client_jws_helpers.js
Adding this claim for non-OB flows causes issues, as the claim is not supported by the AM OAuth 2.0 Provider.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
=> 1404: Only add openbanking_intent_id claim for OB flow

secure-api-gateway-helpers/Chart.yaml
Bump helpers version to 3.0.1 to pick up bug fix from [PR](https://github.com/SecureApiGateway/secure-api-gateway-releases-helpers/pull/18)
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1452
=> 1452: Investigate relenvs v3 keystore issue

postman/v2.0/postman_scripts/client_jws_helpers.js
Fixes a bug introduced by PR: https://github.com/SecureApiGateway/secure-api-gateway-releases/pull/62
The openbanking_intent_id claim need to be set as a field within claims.id_token.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
=> 1404: Set openbanking_intent_id claim within id_token claim

postman/v3.0/collections/Secure API Gateway - Open Banking UK TPP Flows.postman_collection.json, postman/v3.0/collections/Secure API Gateway - Plain FAPI.postman_collection.json, postman/v3.0/postman_scripts/client_jws_helpers.js
Fix the path to client_jws_helpers.js used by v3 collections & bump version to 3.0.2 (which will be released next).
Apply fix:
https://github.com/SecureApiGateway/secure-api-gateway-releases/pull/65 to the v3.0 client_jws_helpers.js
https://github.com/SecureApiGateway/SecureApiGateway/issues/1451
=> 1451: v3 Postman fixes

test-trusted-directory/kustomize/defaults/kustomization.yaml
Remove image override as done in deployments repo
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1476
=> 1476: Build and Deploy SAPIG 3.1.0 to relenv

postman/v3.0/collections/Secure API Gateway - Plain FAPI.postman_collection.json, postman/v3.0/environments/SAPI-G- Plain FAPI.postman_environment.json
Applying the latest changes from dev to the Plain FAPI collection and environment.
This includes changes to work with the TRUSTEDDIR-FQDN URL, and to generate unique software_id values when issuing SSAs.
Setting the AM_REALM to bravo by default so that it works with the core-sandbox-v3 environment OOTB.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1496
=> 1496: Fix v3 Plain FAPI collection and environment

core/kustomize/overlay/7.3.0/defaults/ingress.yaml, secure-api-gateway-helpers/Chart.yaml
All traffic which does not match a more specific rule is now routed to the IG pod. This allows us to reverse proxy identity platform without having to know all of the possible paths that might need to be accessed.
See related IG PR: https://github.com/SecureApiGateway/secure-api-gateway-core/pull/65
https://github.com/SecureApiGateway/SecureApiGateway/issues/1512
=> 1512: SAPI-G ingress pass all traffic to ig pod

ob/kustomize/base/kustomization.yaml
Update OB to use the new release version of release branch
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1665
=> 1665: Update secure-api-gateway-release with changes from Forgeops 

ob/secure-api-gateway-ob/Chart.yaml
Bump other services to 4.9.0 as needed for configmap changes
Issue: https://github.com/secureapigateway/secureapigateway/issues/1682
=> 1682: Use new Helm files to deploy to Relenv

ob/secure-api-gateway-ob/Chart.yaml
Bump ob fapi-pep-as and fapi-pep-rs to `5.0.1`
Issue: https://pingidentity.atlassian.net/browse/OPENIG-9573?atlOrigin=eyJpIjoiY2MxNDI2YTRmY2E2NDE4NGFmYzU1ZTM2ZDgxZjlkMTAiLCJwIjoiaiJ9
=> openIG-9573: SAPIG 5.0.1 Release
