third-party/external-secrets/secretstore.yaml
Change value to be able to be overwritten in pipeline
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/768
=> 768 - Create and deploy new release deployment cluster

secure-api-gateway/Chart.yaml
Use the helm repo to install secure api packages
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/768
=> 768 Release Deployment

kustomize/overlay/7.2.0/defaults/configmap.yaml
https://github.com/SecureApiGateway/SecureApiGateway/issues/768
=> 768: Documenting configmap keys

secure-api-gateway-helpers/Chart.yaml, third-party/Chart.yaml
Add in helpers helm charts to remove dependencies between third party and helpers
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/768
=> 768 release deployment 

.github/workflows/release.yaml
- Updated release workflow:
- Create tag and branch
- Build helm charts and publish them
- Creates Release draft
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
=> 812: release action

secure-api-gateway-helpers/Chart.yaml, third-party/Chart.yaml
=> 931 - Release v0.9.1 of SAPIG

kustomize/overlay/7.2.0/defaults/kustomization.yaml
=> 931 - Prepare 0.9.1 release

kustomize/overlay/7.2.0/defaults/kustomization.yaml, secure-api-gateway-helpers/Chart.yaml, secure-api-gateway/Chart.yaml, third-party/Chart.yaml
- Change the chart descriptions to make more sense
- Increase all parent chart versions and app versions to 1.0.0 & update child versions to 1.0.0 where required
Issue: https://github.com/secureapigateway/secureapigateway/issues/927
=> 927: Change charts descriptions and versions

secure-api-gateway/Chart.yaml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/936
=> 936: release version 1.0.1 for remote-consent-service-user-interface

.github/workflows/readme.md, README.md, secure-api-gateway-helpers/readme.md, secure-api-gateway/readme.md, third-party/readme.md
Add in readmes with installation instructions
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/939
=> 939 standardise helm charts

.github/workflows/release.yaml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1024
=> 1024: Add in new condition for postmans folder

kustomize/overlay/7.2.0/defaults/kustomization.yaml, secure-api-gateway/Chart.yaml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1040
=> 1040: Update required versions for 1.0.3 release

kustomize/overlay/7.2.0/defaults/configmap.yaml
New config map key - RCS_CONSENT_STORE_URI
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099
=> 1099: Add in new Configmap requirement

secure-api-gateway/Chart.yaml
Change RS and RCS to version 2.0.2
Up Chart version for SAPIG to 2.0.2
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1128
=> 1128: Change RS & RCS versions

kustomize/overlay/7.2.0/defaults/configmap.yaml, secure-api-gateway/Chart.yaml
Change needed to configmap value
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1128
=> 1128 - Release 2.0.2 

kustomize/overlay/7.2.0/defaults/kustomization.yaml
Remove IG overwrite as needs to be in customer specification
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1158
=> 1158: Move IG Override tag to customer specification

postman/v2.0/postman_scripts/README.md, postman/v2.0/postman_scripts/client_jws_helpers.js
So that the postman collection can load the helper script - this script will help with creating the client_credential jwt, signing etc.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1171
=> 1171: Add helper postman scripts to git repo

postman/v2.0/postman_scripts/client_jws_helpers.js
Updated Postman helper script to support JARM in /authorize and /par flows.
JARM uses response_type="code" and response_mode="jwt", these params need to be set in the URLs and request JWTs sent to the aforementioned endpoints.
https://github.com/SecureApiGateway/SecureApiGateway/issues/974
=> 974: Adding support for JARM to Postman helper script

.github/workflows/release.yaml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264
=> 1264: Update actions that have deprecations

.github/workflows/release.yaml, secure-api-gateway/Chart.yaml
Commit directly to master instead of having a PR to approve and merge
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1260
=> 1260: Investigate PR runs for GitHub user

.github/workflows/release.yaml, secure-api-gateway/Chart.yaml
Bump versions to 2.3.1 for helm chart & RS
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1272
=> 1272: Create SAPIG version 2.3.1

core/kustomize/overlay/7.3.0/defaults/securebanking/kustomization.yaml, ob/secure-api-gateway-ob/Chart.yaml, secure-api-gateway-helpers/Chart.yaml, third-party/Chart.yaml
Bump versions to 3.0.0
Bump mongodb version to 14.4.1
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
=> 1404: Create and Release SAPIG Core and OB

postman/v3.0/collections/Secure API Gateway - Open Banking UK TPP Flows.postman_collection.json, postman/v3.0/collections/Secure API Gateway - Plain FAPI.postman_collection.json, postman/v3.0/environments/SAPI-G- Plain FAPI.postman_environment.json, postman/v3.0/environments/SAPI-G-Open Banking UK.postman_environment.json, postman/v3.0/postman_scripts/README.md, postman/v3.0/postman_scripts/client_jws_helpers.js
The v3 Open Banking UK collection has been created from the latest development postman collection.
New v3 Plain FAPI collection has been created for use with the core-sandbox-v3 environment.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1451
=> 1451: Add v3 Postman collections

ob/secure-api-gateway-ob/Chart.yaml
Bump OB Chart version to 3.0.1
=> 1460: Create and Deploy Release 3.0.1

ob/secure-api-gateway-ob/Chart.yaml
Bump OB parent chart values and dependancies
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1516
=> 1516: Create release 3.2.0 and deploy

core/kustomize/base/kustomization.yaml, core/kustomize/base/securebanking/application.yaml, ob/kustomize/base/kustomization.yaml, test-trusted-directory/kustomize/base/kustomization.yaml
Tidy up application data
Move patch to core to apply to both core and ob
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1519
=> 1519: Move Patch for existing secrets to Core kustomize files

ob/kustomize/base/kustomization.yaml, ob/secure-api-gateway-ob/Chart.yaml
Bump chart.yaml and update OB Kustomize Path
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602
=> 1606: Build and Deploy SAPIG 4.0.0

ob/kustomize/base/kustomization.yaml, ob/secure-api-gateway-ob/Chart.yaml
Bump chart version with RS and RCS
Update kustomize reference path
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1625
=> 1625: SAPIG Release 4.0.3 - Further OB V4 Support

ob/secure-api-gateway-ob/Chart.yaml
Bump Chart Version and RS version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1664
=> 1664: Prepare SAPIG 4.0.5

core/kustomize/base/kustomization.yaml
Update kustomize overlay to remove deleted secret from base
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1665
=> 1665: Update secure-api-gateway-release with changes from Forgeops 

ob/secure-api-gateway-ob/Chart.yaml
Bump Helm versions and UI version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1680
=> 1680: Deploy 4.0.5 UI to ob-sandbox-v4

core/secure-api-gateway-core/Chart.yaml, core/secure-api-gateway-core/readme.md, ob/secure-api-gateway-ob/Chart.yaml
- Add in new umbrella chart for Core
- Amend OB chart for new components
- Typos
Issues: https://github.com/SecureApiGateway/SecureApiGateway/issues/1682
=> 1682: Use new Helm files to deploy to Relenv

postman/v4.0/postman_scripts/README.md, postman/v4.0/postman_scripts/SAPI-G- v4.x.x- Open Banking UK.postman_environment.json, postman/v4.0/postman_scripts/Secure API Gateway v4.x - Open Banking UK TPP Flows.postman_collection.json, postman/v4.0/postman_scripts/client_jws_helpers.js
This is published at https://postman.ob-sandbox-v4.forgerock.financial/
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1695
=> 1695: Capture Postman Published v4 Postman Collection

core/secure-api-gateway-core/Chart.yaml, ob/secure-api-gateway-ob/Chart.yaml
Update chart versions and dependencies to 5.0.0 for ob and core
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1703
=> 1703: Create SAPIG 5.0.0

core/secure-api-gateway-core/Chart.yaml, ob/secure-api-gateway-ob/Chart.yaml
Create SAPIG 5.0.3
Issue: https://pingidentity.atlassian.net/jira/software/c/projects/OPENIG/boards/1322
=> OpenIG-9650: SAPIG 5.0.3 Release
